- name: Disable copr
  community.general.copr:
    name: solopasha/hyprland
    state: enabled
  become: true

- name: Install build dependencies
  ansible.builtin.package:
    pkg:
      - lz4-devel
      - wayland-devel
      - wayland-protocols-devel
    state: present
  become: true
  when: build_required
