- name: Clone or update awww repository
  ansible.builtin.git:
    repo: "https://codeberg.org/LGFae/awww.git"
    dest: "/usr/src/awww"
    version: "main"
    update: yes
  register: awww_git_result
  become: true

- name: Define awww_build_required
  ansible.builtin.set_fact:
    awww_build_required: "{{ awww_git_result.before != awww_git_result.after }}"

- name: "Checking config for {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: distribution_config
  delegate_to: localhost

- name: "Run Tasks for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: distribution_config.stat.exists

- name: Build awww (release)
  ansible.builtin.command: cargo build --release --locked
  args:
    chdir: "/usr/src/awww"
  become: true
  notify: Remove build dependencies
  when: awww_build_required

- name: Install release binaries
  vars:
    binaries:
      - awww
      - awww-daemon
  ansible.builtin.copy:
    src: "/usr/src/awww/target/release/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    remote_src: true
  loop: "{{ binaries }}"
  become: true
  when: awww_build_required

- name: Create awww config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/hypr/scripts"
    state: directory

- name: Copy wallpaper script
  ansible.builtin.copy:
    src: "files/wallpaper.sh"
    dest: "{{ ansible_user_dir }}/.config/hypr/scripts/wallpaper.sh"
    mode: "0755"

- name: Copy wallpapers
  ansible.builtin.copy:
    src: "files/wallpapers"
    dest: "{{ ansible_user_dir }}/Pictures/Wallpapers"

