- name: Clone or update awww repository
  ansible.builtin.git:
    repo: "https://codeberg.org/LGFae/awww.git"
    dest: "/usr/src/awww"
    version: "main"
    update: yes
  register: git_result
  become: true

- name: Define build_required
  ansible.builtin.set_fact:
    build_required: git_result.before != git_result.after

- name: Build awww (release)
  ansible.builtin.command: cargo build --release --locked
  args:
    chdir: "/usr/src/awww"
  become: true
  notify: Remove build dependencies
  when: build_required

- name: Install release binaries
  vars:
    binaries:
      - awww
      - awww-daemon
  ansible.builtin.copy:
    src: "/usr/src/awww/target/release/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    remote_src: true
  loop: "{{ binaries }}"
  become: true
  when: build_required

- name: Create awww config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/hypr/scripts"
    state: directory

- name: Copy wallpaper script
  ansible.builtin.copy:
    src: "files/wallpaper.sh"
    dest: "{{ ansible_user_dir }}/.config/hypr/scripts/wallpaper.sh"
    mode: "0755"

- name: Copy wallpapers
  ansible.builtin.copy:
    src: "files/wallpapers"
    dest: "{{ ansible_user_dir }}/Pictures/Wallpapers"

