- name: Install {{ name }} with flatpak
  community.general.flatpak:
    name: "{{ flathub_name }}"
    state: present
    method: user

- name: Add Desktop Entry for {{ name }}
  ansible.builtin.template:
    src: "templates/application.desktop.j2"
    dest: "{{ home }}/.local/share/applications/{{ flathub_name }}.desktop"
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true

