- name: "uwsm | Install meson"
  ansible.builtin.package:
    name: meson
    state: present
  become: true

- name: "uwsm | Install dependancies"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pyxdg
    - ninja-build
    - scdoc
  become: true

- name: "uwsm | Clone the source repository"
  ansible.builtin.git:
    repo: "{{ source_url }}"
    dest: "{{ dest }}"
    version: "v0.20.5"

- name: "uwsm | Setup meson"
  ansible.builtin.command:
    chdir: "{{ dest }}"
    cmd: "meson setup --prefix=/usr/local -Duuctl=enabled -Dfumon=enabled -Duwsm-app=enabled build"

- name: "uwsm | Build from source"
  ansible.builtin.command:
    chdir: "{{ dest }}"
    cmd: "meson install -C build"
  become: true

