- name: Disable outdated copr
  community.general.copr:
    name: solopasha/hyprland
    state: disabled
  become: true

- name: Enable copr
  community.general.copr:
    name: sdegler/hyprland
    state: enabled
  become: true

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Install hyprpolkitagent
  ansible.builtin.package:
    name: hyprpolkitagent
    state: present
  become: true
  notify: Reload systemd daemon
