- name: Install dependencies
  ansible.builtin.package:
    pkg:
      - hyprland
      - hyprutils
      - qt5-qtwayland
      - qt6-qtwayland
      - dbus-broker
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - mako
  become: true
  notify: Restart dbus-broker

- name: Create xdg-desktop-portal-hyprland config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/xdg-desktop-portal"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "755"
  become: true

- name: Copy xdg-desktop-portal-hyprland config
  ansible.builtin.copy:
    src: "files/hyprland-portals.conf"
    dest: "{{ ansible_user_dir }}/.config/xdg-desktop-portal/hyprland-portals.conf"
    mode: "755"
