- name: Install xdg-desktop-portal-hyprland
  ansible.builtin.package:
    name: xdg-desktop-portal-hyprland
    state: present
  become: true

- name: Create xdg-desktop-portal-hyprland config directory
  ansible.builtin.file:
    path: "{{ config }}/xdg-desktop-portal"
    state: directory
    mode: "755"
  become: true

- name: Copy xdg-desktop-portal-hyprland config
  ansible.builtin.copy:
    src: "files/hyprland-portals.conf"
    dest: "{{ config }}/xdg-desktop-portal/hyprland-portals.conf"
    mode: "755"

- name: Install hyprpolkitagent
  ansible.builtin.package:
    name: hyprpolkitagent
    state: present
  become: true

- name: Start hyprpolkitagent
  ansible.builtin.systemd:
    name: hyprpolkitagent
    enabled: true
    scope: user
    state: started

- name: Install qt5-wayland
  ansible.builtin.package:
    name: qt5-qtwayland-devel
    state: present
  become: true

- name: Install qt6-wayland
  ansible.builtin.package:
    name: qt6-qtwayland-devel
    state: present
  become: true

- name: Install dbus-broker
  ansible.builtin.package:
    name: dbus
    state: present
  become: true
  notify:
    - Restart dbus

- name: Build uwsm from source
  vars:
    source_url: "https://github.com/Vladimir-csp/uwsm.git"
    dest: "{{ build }}/uwsm"
  ansible.builtin.include_tasks: "uwsm.yml"

- name: Install hyprland
  ansible.builtin.package:
    name: hyprland
    state: present
  become: true
