- name: "Checking config for {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: distribution_config
  delegate_to: localhost

- name: "Run Tasks for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: distribution_config.stat.exists

- name: Check if hyprland is installed
  ansible.builtin.stat:
    path: /usr/bin/Hyprland
  register: hyprland
  changed_when: false
  failed_when: false

- name: Installing Hyprland
  ansible.builtin.include_tasks: ./install.yml
  when: not hyprland.stat.exists

- name: Check if graphical.target is the default target
  ansible.builtin.shell: systemctl get-default
  register: systemd_default
  changed_when: false

- name: Set graphical.target as the default target
  ansible.builtin.shell: systemctl set-default graphical.target
  when: systemd_default.stdout != 'graphical.target'
  become: true
