- name: "uwsm | Install meson"
  ansible.builtin.package:
    name: meson
    state: present
  become: true

- name: "uwsm | Install dependancies"
  ansible.builtin.package:
    name:
      - python3-pyxdg
      - ninja-build
      - scdoc
    state: present
  become: true

- name: "uwsm | Clone the source repository"
  ansible.builtin.git:
    repo: "{{ source_url }}"
    dest: "{{ dest }}"
    version: "v0.20.5"

- name: "uwsm | Setup meson"
  ansible.builtin.command:
    chdir: "{{ dest }}"
    cmd: "meson setup --prefix=/usr/local -Duuctl=enabled -Dfumon=enabled -Duwsm-app=enabled build"

- name: "uwsm | Build from source"
  ansible.builtin.command:
    chdir: "{{ dest }}"
    cmd: "meson install -C build"
  become: true

- name: Create uwsm config directory
  ansible.builtin.file:
    path: "{{ config }}/uwsm"
    state: directory
    mode: "755"

- name: uwsm | Copy config
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ config }}/uwsm/{{ item }}"
    mode: "755"
  with_items:
    - env
    - env-hyprland
