- name: "Checking config for {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: distribution_config
  delegate_to: localhost

- name: "Run Tasks for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: distribution_config.stat.exists

- name: Install packages
  ansible.builtin.package:
    name:
      # Development
      - tokei
      - lazygit
      - httpie
      # Utils
      - zoxide
      - exa
      - bat
      - fd-find
      - nnn
      - ripgrep
      - aspell
      - btop
      - hyperfine
      - ncdu
      - qemu
      - tealdeer
      - unzip
      - tar
      - ffmpeg
      # Icons
      - papirus-icon-theme
    state: present
  become: true
