add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "rose-pine"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
symbol = " "

