- name: Cleanup vala-panel-appmenu downloaded tar
  ansible.builtin.file:
    path: "/tmp/{{ vala_appmenu_file }}.tar.gz"
    state: absent
  become: true

- name: Cleanup vala-panel-appmenu extracted directory
  ansible.builtin.file:
    path: "/tmp/{{ vala_appmenu_file }}"
    state: absent
  become: true

