- name: "Checking for: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: distribution_config
  delegate_to: localhost

- name: "Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: distribution_config.stat.exists

- name: Install
  ansible.builtin.package:
    name: starship
    state: present
  become: true

- name: Add startship to fish
  ansible.builtin.blockinfile:
    path: "{{ config }}/fish/config.fish"
    block: "starship init fish | source"
    insertafter: EOF

- name: Copy config files
  ansible.builtin.copy:
    src: "files/"
    dest: "{{ config }}"

