# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
if uwsm check may-startup; then
    exec uwsm start hyprland.desktop
fi

