- name: Cleanup downloaded node archive
  ansible.builtin.file:
    path: "/tmp/{{ node_file }}"
    state: absent
  become: true

- name: Remove extracted node directory
  ansible.builtin.file:
    path: /tmp/node-v{{ node_latest_version }}-{{ nodeos }}-{{ nodearch }}
    state: absent
  become: true

