add_newline = false
format = """$directory$character"""
palette = "rose-pine"
right_format = """$all"""
command_timeout = 1000

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[git_branch]
symbol = " "

