- name: Ensure kitty directory exists in .config
  ansible.builtin.file:
    path: "{{ config }}/kitty"
    state: directory
    mode: '0755'

- name: Copy kitty configuration
  ansible.builtin.copy:
    src: "files/"
    dest: "{{ config }}/kitty/"
    mode: "0644"
