- name: "Checking config for {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: distribution_config
  delegate_to: localhost

- name: "Run Tasks for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: distribution_config.stat.exists

- name: Install hypr tool
  ansible.builtin.package:
    name: hyprlock
    state: present
  become: true

- name: Copy hyprland config
  ansible.builtin.copy:
    src: files/
    dest: "{{ ansible_user_dir }}/.config/hypr/"

    mode: "0644"
