- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present
  become: true
    
- name: Copy config files
  ansible.builtin.copy:
    src: "files/"
    dest: "{{ config }}/fish/"
