- name: Checking version
  ansible.builtin.command:
    cmd: "{{ node_bin }}/sass --version"
  register: sass_version
  changed_when: false
  failed_when: false

- name: Querying last sass version
  ansible.builtin.uri:
    url: https://registry.npmjs.org/sass
  register: last_sass_version_query
  changed_when: false

- name: Define current sass version
  ansible.builtin.set_fact:
    current_sass_version: "{{ sass_version.stdout.split(' ')[0] }}"

- name: Define last sass version
  ansible.builtin.set_fact:
    last_sass_version: "{{ last_sass_version_query.json['dist-tags']['latest'] }}"

- name: Show current sass version
  ansible.builtin.debug:
    var: current_sass_version

- name: Show last sass version
  ansible.builtin.debug:
    var: last_sass_version

- name: Install sass
  community.general.npm:
    name: sass
    global: yes
  environment:
    PATH: "{{ node_bin }}:{{ ansible_env.PATH }}"
  when: current_sass_version != last_sass_version

