- name: Check typescript version
  ansible.builtin.command:
    cmd: "{{ node_bin }}/tsc --version"
  register: tsc_version
  changed_when: false
  failed_when: false

- name: Querying last typescript version
  ansible.builtin.uri:
    url: https://registry.npmjs.org/typescript
  register: last_tsc_version_query
  changed_when: false

- name: Define current typescript version
  ansible.builtin.set_fact:
    last_tsc_version: "Version {{ last_tsc_version_query.json['dist-tags']['latest'] }}"

- name: Show typecript version
  ansible.builtin.debug:
    var: tsc_version.stdout

- name: Show last typescript version
  ansible.builtin.debug:
    var: last_tsc_version

- name: Install typescript
  community.general.npm:
    name: typescript
    global: yes
  environment:
    PATH: "{{ node_bin }}:{{ ansible_env.PATH }}"
  when: tsc_version.stdout != last_tsc_version

