- name: Install Quickshell dependencies (Fedora)
  ansible.builtin.dnf:
    name:
      - gojq
      - python3-pillow
      - python3-pywayland
      - python3-psutil
      - hyprpicker
      - cliphist
      - ydotool
      # End 4 Shell dependencies
      - qt6-qt5compat
    state: present
  become: true
