# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
if uwsm check may-start; then
    exec uwsm start hyprland.desktop
fi

# Hyprland startup
if uwsm check may-start; then
  exec uwsm start hyprland.desktop
fi
