- name: "Add 1Password Key"
  ansible.builtin.rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present
  become: true

- name: "Add APT Repo"
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    state: present
  become: true

- name: "Install 1Password"
  ansible.builtin.dnf5:
    name: 1password-cli
    state: present
    update_cache: true
  become: true
