- name: Checking if hyprpanel is installed
  ansible.builtin.stat:
    path: /usr/bin/hyprpanel
  register: hyprpanel_check
  changed_when: false
  failed_when: false

- name: Installing hyprpanel
  ansible.builtin.include_tasks: install.yml
  when: hyprpanel_check.stat.exists == false

- name: Ensure .config/hyprpanel exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/hyprpanel"
    state: directory
    mode: "0755"

- name: Copy hyprpanel configuration
  ansible.builtin.copy:
    src: "files/config.json"
    dest: "{{ansible_user_dir}}/.config/hyprpanel/config.json"

