- name: Check if ghostty is installed
  ansible.builtin.stat:
    path: /usr/bin/ghostty
  register: ghostty
  changed_when: false
  failed_when: false

- name: Install ghostty
  ansible.builtin.include_tasks: install.yml
  when: ghostty.stat.exists == false

- name: Copy ghostty configuration
  ansible.builtin.copy:
    src: "files/ghostty"
    dest: "{{ config }}"

