- name: Getting version information
  ansible.builtin.command: "zellij --version"
  register: current_version
  changed_when: false
  failed_when: false

- name: Query latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/zellij-org/zellij/releases/latest?mode=json
  register: latest_version
  changed_when: false

- name: define zellij current version
  ansible.builtin.set_fact:
    zellij_current_version: "{{ current_version.stdout.split(' ')[1] }}"

- name: define zellij latest version
  ansible.builtin.set_fact:
    zellij_latest_version: "{{ latest_version.json.tag_name | replace('v', '') }}"

- name: "Define zellij ARCH"
  ansible.builtin.set_fact:
    zellij_arch: "{{ ansible_machine | lower }}"

- name: Show current version
  ansible.builtin.debug:
    var: zellij_current_version

- name: Show latest version
  ansible.builtin.debug:
    var: zellij_latest_version

- name: Show ARCH
  ansible.builtin.debug:
    var: zellij_arch

- name: Downloading latest version
  ansible.builtin.unarchive:
    src: "https://github.com/zellij-org/zellij/releases/download/{{ latest_version.json.tag_name }}/zellij-{{ zellij_arch }}-unknown-linux-musl.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: true
  when: zellij_latest_version != zellij_current_version
  become: true
